### ISSUE TITLE
Lyrics parser cuts lines around annotations

### ISSUE THREAD

**Issue by maelchiotti** [fedecalendino/wrap-genius#2]
Hi, now that I'm using your project to get lyrics, I noticed some strange behaviour.

Lines are cut around Genius' annotations, when of course they souldn't.

For instance, with [this song](https://genius.com/Maisie-peters-brooklyn-lyrics), which contains an annotation on `Gemini` and on `straight to 42nd`:

Lyrics on Genius:
> Village is dead
> Gemini panic
> Quick out of bed

Lyrics parsed:
> 'Village is dead', 'Gemini', ' panic', 'Quick out of bed'

Lyrics on Genius:
> Land at 11, straight to 42nd, it's colder

Lyrics parsed:
> 'Land at 11, ', 'straight to 42nd', ", it's colder"

I noticed that it happens around each Genius' annotation, and so far only there.

**Comment by fedecalendino** [comment]
Hi again @maelchiotti !

Oh right, good catch! I think I know why this might be happening, I'll try to fix :)

Fede.

edit:

Much better now on **v1.7.2**

```python
song = g.get_song(song_id=6914353)
print("Song:", song.title_with_featured)
print(" * released date:", song.release_date_for_display)
print(" * album:", song.album)

print()
print("Artist:", song.artist)

lyrics = song.lyrics
print()
print("Lyrics:")
print('\n'.join(lyrics))
```

```
Song: Brooklyn
 * released date: August 11, 2021
 * album: You Signed Up For This (741845)

Artist: Maisie Peters (997186)

Lyrics:
[Verse 1]
Village is dead
Gemini panic
Quick out of bed
Shuttle to Gatwick
Noodles for breakfast
Terrible tickets
I hate your tracksuit
Sister, I missed this

...
```

**Comment by maelchiotti** [comment]
Tried it on a few songs and didn't notice any issue so far!
