### ISSUE TITLE
Lyrics for Instrumental Tracks

### ISSUE THREAD

**Issue by duplaja** [fedecalendino/wrap-genius#6]
Hello! Loving this project.

One small suggestion I'd make is instead of returning nothing when a track is instrumental, returning some kind of indicator, even what Genius sends ("This song is an instrumental").

I've included an example of such a track here: https://genius.com/Julianna-barwick-adventurer-of-the-family-annotated

Thank you!

**Comment by fedecalendino** [comment]
Hi Dan!

That is a great idea! At the moment I'm super busy while moving to another home.
I'll try to get back on this as soon as I'm settled.


In the meantime, feel free to give it a try and send me a PR.


Cheers,
Fede.

**Comment by fedecalendino** [comment]
Hi Dan!

Sorry for the super late response for this. I'm still super busy right now, but I'll happily accept a PR for this.

Cheers,
Fede.
